version: '3.4'

services:
  masstransit.saga:
    image: ${DOCKER_REGISTRY-}masstransitpoc
    build:
      context: .
      dockerfile: src/MassTransit.POC/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    env_file:
      - ./poc.env
    ports:
      - "5500:80"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
  
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB:-POC}", "-U", "${POSTGRES_USER:-debug}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-POC}
      POSTGRES_USER: ${POSTGRES_USER:-debug}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-debug}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack
    healthcheck:
      test: awslocal sns list-topics && awslocal sqs list-queues
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns,sqs
      
